# Generated by Django 5.0.6 on 2024-07-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_like_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/posts/'),
        ),
    ]
