# Generated by Django 5.0.6 on 2024-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/posts/'),
        ),
    ]
