# Generated by Django 5.0.6 on 2024-08-19 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_remove_profile_avatar_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_picture',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
