# Generated by Django 5.0.6 on 2024-08-19 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_profile_picture_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Picture',
            new_name='Avatar',
        ),
    ]
